#this pipeline will be trigger to run by master branch of github repo. 
trigger:
 - master

#add variables
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'myacrcontainerregistry001'
          repository: 'app1'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'kube-artifacts'
          publishLocation: 'Container'
          MaxArtifactSize: 1
      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          connectionType: 'kubernetesServiceConnection'
          kubernetesServiceConnection: 'default-svc-conn'
          namespace: 'dev'
          manifests: 'k8s-deployment.yaml'

